apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-server
data:
  values.yaml: |
    Secret: {{ .Values.global.Secret }}
    Logger: {{ toYaml .Values.global.Logger | nindent 6 }}
    Gateway:
      IssuerService: http://{{ printf "%s.%s.%s" "issuer-server" .Release.Namespace "svc.cluster.local" }}
    Sync:
      GrpcClient:
        Listen: grpc-server.{{ .Release.Namespace }}.svc.cluster.local:80
      Redis: {{ toYaml .Values.global.Sync.Redis | nindent 8 }}
      Target: {{ .Values.global.Sync.Target }}