dependencies:  
    - name: grpc
      version: 0.1.0
      appVersion: 0.1.0
      repository: 'file:///charts/grpc' 

    - name: issuer-server
      version: 0.1.0
      repository: 'file:///charts/issuer'

    - name: gateway-server
      version: 0.1.0
      repository: 'file:///charts/gateway'
