{{ if eq .Values.global.Sync.Target "GRPC" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grpc.fullname" . }}
data:
  values.yaml: |
    Secret: {{ .Values.global.Secret }}
    Logger: {{ toYaml .Values.global.Logger | nindent 6 }}
    Sync:
      Target: {{ .Values.global.Sync.Target }}
      GrpcServer:
        Port: 80
{{ end }}
