apiVersion: v1
kind: Service
metadata:
  name: {{ include "issuer.fullname" . }}
  labels:
    {{- include "issuer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 10086
      targetPort: cert-port
      protocol: TCP
      name: cert-port
  selector:
    {{- include "issuer.selectorLabels" . | nindent 4 }}
